export default [
  {
    title: 'The Getaway',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/The Getaway.mp3',
  },
  {
    title: 'Dark Necessities',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Dark Necessities.mp3',
  },
  {
    title: 'We Turn Red',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/We Turn Red.mp3',
  },
  {
    title: 'The Longest Wave',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/The Longest Wave.mp3',
  },
  {
    title: 'Goodbye Angels',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Goodbye Angels.mp3',
  },
  {
    title: 'Sick Love',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Sick Love.mp3',
  },
  {
    title: 'Go Robot',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Go Robot.mp3',
  },
  {
    title: 'Feasting On The Flowers',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Feasting On The Flowers.mp3',
  },
  {
    title: 'Detroit',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Detroit.mp3',
  },
  {
    title: 'This Ticonderoga',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/This Ticonderoga.mp3',
  },
  {
    title: 'Encore',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Encore.mp3',
  },
  {
    title: 'The Hunter',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/The Hunter.mp3',
  },
  {
    title: 'Dreams Of A Samurai',
    artist: 'Red Hot Chili Peppers',
    cover: './src/assets/the-getaway-cover.jpg',
    file: './src/assets/The Getaway/Dreams Of A Samurai.mp3',
  },
];
